apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend-deployment
spec:
  selector:
    matchLabels:
      app: krakend
  replicas: 1 # Switch to 2 in PROD env.
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
      - name: krakend
        image: 7997/krakend:25fe19d32283e9f8f45669f52a91486c19a09ad2 # Note: Image for ARM64 arch
        ports:
        - containerPort: 8080
        # imagePullPolicy: Never # Decomment when owr image is available
        command: [ "/usr/bin/krakend" ]
        args: [ "run", "-d", "-c", "/etc/krakend/krakend.json", "-p", "8080" ]
        env:
        - name: KRAKEND_PORT
          value: "8080"
        resources:
          limits: # Note: Check if resources are enough
            memory: "256Mi"
            cpu: "500m"